version: "3.8"

name: animepipeline

services:
  animepipeline:
    image: lychee0/animepipeline:latest
    restart: always
    volumes:
      - ./animepipeline:/app/conf
      - ./downloads:/downloads

  qb:
    image: linuxserver/qbittorrent:latest
    restart: always
    environment:
      - PUID=1026
      - PGID=100
    volumes:
      - ./allinone/qb-config:/config
      - ./downloads:/downloads
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "48008:48008"
      - "48008:48008/udp"
      - "8091:8080"
#  qb-ee:
#    image: superng6/qbittorrentee:4.4.5.10
#    restart: always
#    environment:
#      - PUID=1026
#      - PGID=100
#    volumes:
#      - ./allinone/qb-config:/config
#      - ./downloads:/downloads
#    ports:
#      - "6881:6881"
#      - "6881:6881/udp"
#      - "48008:48008"
#      - "48008:48008/udp"
#      - "8091:8080"
