version: "3.8"

name: animepipeline-dev

services:
  qb:
    image: superng6/qbittorrentee:4.4.5.10
    restart: always
    environment:
      - PUID=1026
      - PGID=100
    volumes:
      - ./docker/qb-config:/config
      - ./docker/downloads:/downloads
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "48008:48008"
      - "48008:48008/udp"
      - "8091:8080"
