name: CI-test-cli

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  workflow_dispatch:

env:
  GITHUB_ACTIONS: true

jobs:
  cli:
    strategy:
      matrix:
        os-version: ["ubuntu-latest"]
        python-version: ["3.9"]
        poetry-version: ["1.8.3"]

    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Build package
        run: |
          make build

      - name: Install package and test CLI
        run: |
          cd dist
          pip install *.whl

          ap-rename -h
          ap-btf -h
