name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  pypi:
    strategy:
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.8.3"]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Build package
        run: |
          make build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API }}

  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: lychee0
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            - lychee0/animepipeline:latest
            - lychee0/animepipeline:${{ github.ref }}

  github:
    needs: [pypi, docker]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Release
        uses: softprops/action-gh-release@v2
